name: Android Ci Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "README_EN.md"
      - "doc/*"
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
          cache: gradle
      - name: Set up environment variables
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/tools/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
      - name: Accept licenses
        run: yes | sdkmanager --licenses
      - name: Build with Gradle Release
        shell: bash
        run: ./gradlew assembleRelease
      - uses: actions/upload-artifact@v3
        with:
          name: WooBoxForMIUI_Release
          path: "app/build/outputs/apk/release/*.apk"
