name: Android Ci Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "README_EN.md"
      - "doc/*"
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
      - uses: gradle/gradle-build-action@v2
      - run: 
          ./gradlew :app:packageRelease
      - uses: actions/upload-artifact@v3
        with:
          name: WooBoxForMIUI_Release
          path: "app/build/outputs/apk/release/*.apk"
