name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2   

    - name: Execute Gradle build
      run: 
        ./gradlew :app:packageRelease
    
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: WooBoxForMIUI_Release
        path: "app/build/outputs/apk/release/*.apk"
